# California Restaurant "Likes" Prediction Using Foursquare API and Machine Learning

Khalid Meguenni<br>
Capstone Project <br>
IBM Data Science Professional Certificate <br>

## 1. Introduction

California boasts an incredibly diverse collection of restaurants catering to different palettes and appetites. A large part of marketing for a modern restaurant (or any company) is social media, where the number of "likes" that the company can receive will dictate its brand and image to the general public. <br>

For a new business owner (or existing company) to open a new restaurant in California, knowing ahead of time the potential social media image they can have would provide an excellent solution to the ever present business problem of uncertainty. In this case the uncertainty is regarding performance of social media presence. 
<br>

We can mitigate this uncertainty through leveraging data gathered from FourSquare's API, specifically, we are able to scrape "likes" data of different restaurants directly from the API as well as their location and category of cuisine. The question we will try to address is, how accurately can we predict the amount of "likes" a new restaurant opening in this region can expect to have based on the type of cuisine it will serve and which city in California it will open in. (For the purposes of this analysis, we will contain the geographical scope of analysis to three heavily populated cities in California, namely San Francisco, Los Angeles, and San Diego). 
<br>

Leveraging this data will solve the problem as it allows the new business owner (or existing company) to make preemptive business decisions regarding opening the restaurant in terms of whether it is feasible to open one in this region and expect good social media presence, what type of cuisine and which city of three would be the best. This project will analyze and model the data via machine learning through comparing both linear and logistic regressions to see which method will yield better predictive capabilities after training and testing. 
<br>

Let us begin by importing the necessary packages.

In [1]:
import numpy as np 

import pandas as pd 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json

from geopy.geocoders import Nominatim 

import requests
from pandas.io.json import json_normalize 


import matplotlib.cm as cm
import matplotlib.colors as colors


import folium 

from urllib.request import urlopen
from bs4 import BeautifulSoup


import matplotlib.pyplot as plt
import pylab as pl

from sklearn import linear_model
from sklearn.metrics import jaccard_similarity_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import log_loss
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error, r2_score
import itertools


print('Libraries imported.')

Libraries imported.

# 2. Data

## 2.1 Data Scraping and Cleaning

In this section we will first retrieve the geographical coordinates of the three cities (San Francisco, Los Angeles, and San Diego). Then, we will leverage the FourSquare API to obtain URLs that lead to the raw data in JSON form. We will speerately scrape the raw data in these URLs in order to retrieve the following columns: "name", "categories", "latitude", "longitude". and "id" for each city. We can also provide another column ("city") to indicate which city the restaurants are from. 
<br>

It is important to note that the extracts are not of every restaurant in those cities but rather all of the restaurants within a 1000KM range of the geographical coordinates that geolocator was able to provide. However, the extraction from the FourSquare API actually obtains venue data so it will include venues other than restaurants such as concert halls, stores, libraries etc. As such, this means that the data will need to be further cleaned somewhat manually by removing all of the non-restaurant rows. Once this is complete, we have a shortened by cleaned list to pull "likes" data. The reason the cleaning takes precedence is mainly that pulling the "likes" data is the computing process which takes the longest time in this project so we want to make sure we are not pulling information that will end up being dropped anyways.

The "id" is an important column as it will allow us to further pull the "likes" from the API. We can retreive the "likes" based on the restaurant "id" and then append it to the data frame. Once this is complete, we finally name the dataframe 'raw_dataset' as it is the most complete compiled form before needing any processing for analysis via machine learning.

In [2]:
address1 = 'San Francisco, California'

geolocator = Nominatim()
location1 = geolocator.geocode(address1)
latitude1 = location1.latitude
longitude1 = location1.longitude
print('The geograpical coordinate of {} are {}, {}.'.format(address1, latitude1, longitude1))


address2 = 'Los Angeles, California'

geolocator = Nominatim()
location2 = geolocator.geocode(address2)
latitude2 = location2.latitude
longitude2 = location2.longitude
print('The geograpical coordinate of {} are {}, {}.'.format(address2, latitude2, longitude2))

address3 = 'San Diego, California'

geolocator = Nominatim()
location3 = geolocator.geocode(address3)
latitude3 = location3.latitude
longitude3 = location3.longitude
print('The geograpical coordinate of {} are {}, {}.'.format(address3, latitude3, longitude3))

/usr/local/lib/python3.6/dist-packages/geopy/geocoders/osm.py:143: UserWarning: Using Nominatim with the default "geopy/1.17.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  UserWarning

The geograpical coordinate of San Francisco, California are 37.7790262, -122.4199061.
The geograpical coordinate of Los Angeles, California are 34.0536909, -118.2427666.
The geograpical coordinate of San Diego, California are 32.7174209, -117.1627714.

In [3]:
CLIENT_ID = '1AJETP2F5JJMQ22BA33HNS2YNOF0QKT5HDAJNHBRMK04LQVC' # your Foursquare ID
CLIENT_SECRET = 'KEVIFVL2Y0BINL5HGRGRTWGOKUETUMVY5L124X1BJHVBDEOD' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)


LIMIT = 100 # limit of number of venues returned by Foursquare API
radius = 1000 # define radius

# create URLs
url1 = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    latitude1, 
    longitude1, 
    radius, 
    LIMIT)


# create URLs
url2 = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    latitude2, 
    longitude2, 
    radius, 
    LIMIT)


# create URLs
url3 = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    latitude3, 
    longitude3, 
    radius, 
    LIMIT)

print(url1, url2, url3)

Your credentails:
CLIENT_ID: 1AJETP2F5JJMQ22BA33HNS2YNOF0QKT5HDAJNHBRMK04LQVC
CLIENT_SECRET:KEVIFVL2Y0BINL5HGRGRTWGOKUETUMVY5L124X1BJHVBDEOD
https://api.foursquare.com/v2/venues/explore?&client_id=1AJETP2F5JJMQ22BA33HNS2YNOF0QKT5HDAJNHBRMK04LQVC&client_secret=KEVIFVL2Y0BINL5HGRGRTWGOKUETUMVY5L124X1BJHVBDEOD&v=20180605&ll=37.7790262,-122.4199061&radius=1000&limit=100 https://api.foursquare.com/v2/venues/explore?&client_id=1AJETP2F5JJMQ22BA33HNS2YNOF0QKT5HDAJNHBRMK04LQVC&client_secret=KEVIFVL2Y0BINL5HGRGRTWGOKUETUMVY5L124X1BJHVBDEOD&v=20180605&ll=34.0536909,-118.2427666&radius=1000&limit=100 https://api.foursquare.com/v2/venues/explore?&client_id=1AJETP2F5JJMQ22BA33HNS2YNOF0QKT5HDAJNHBRMK04LQVC&client_secret=KEVIFVL2Y0BINL5HGRGRTWGOKUETUMVY5L124X1BJHVBDEOD&v=20180605&ll=32.7174209,-117.1627714&radius=1000&limit=100

In [4]:
# scrape the data from the generated URLs

results1 = requests.get(url1).json()
results1

results2 = requests.get(url2).json()
results2

results3 = requests.get(url3).json()
results3

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']
    

### first city ###    
    
venues1 = results1['response']['groups'][0]['items']
nearby_venues1 = json_normalize(venues1) # flatten JSON

# filter columns
filtered_columns1 = ['venue.name', 'venue.categories', 'venue.location.lat', 
                    'venue.location.lng', 'venue.id']
nearby_venues1 =nearby_venues1.loc[:, filtered_columns1]

# filter the category for each row
nearby_venues1['venue.categories'] = nearby_venues1.apply(get_category_type, axis=1)

# clean columns
nearby_venues1.columns = [col.split(".")[-1] for col in nearby_venues1.columns]


### second city ###

venues2 = results2['response']['groups'][0]['items']
nearby_venues2 = json_normalize(venues2) # flatten JSON

# filter columns
filtered_columns2 = ['venue.name', 'venue.categories', 'venue.location.lat', 
                    'venue.location.lng', 'venue.id']
nearby_venues2 =nearby_venues2.loc[:, filtered_columns2]

# filter the category for each row
nearby_venues2['venue.categories'] = nearby_venues2.apply(get_category_type, axis=1)

# clean columns
nearby_venues2.columns = [col.split(".")[-1] for col in nearby_venues2.columns]


### third city ###

venues3 = results3['response']['groups'][0]['items']
nearby_venues3 = json_normalize(venues3) # flatten JSON

# filter columns
filtered_columns3 = ['venue.name', 'venue.categories', 'venue.location.lat', 
                    'venue.location.lng', 'venue.id']
nearby_venues3 =nearby_venues3.loc[:, filtered_columns3]

# filter the category for each row
nearby_venues3['venue.categories'] = nearby_venues3.apply(get_category_type, axis=1)

# clean columns
nearby_venues3.columns = [col.split(".")[-1] for col in nearby_venues3.columns]





print('{} venues were returned by Foursquare.'.format(nearby_venues1.shape[0]))
print('{} venues were returned by Foursquare.'.format(nearby_venues2.shape[0]))
print('{} venues were returned by Foursquare.'.format(nearby_venues3.shape[0]))

100 venues were returned by Foursquare.
100 venues were returned by Foursquare.
100 venues were returned by Foursquare.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:28: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:45: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:62: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

In [0]:
# add locations data to the data sets of each city

nearby_venues1['city'] = 'San Francisco'
nearby_venues2['city'] = 'Los Angeles'
nearby_venues3['city'] = 'San Diego'

In [0]:
# combine the three cities into one data set

nearby_venues = nearby_venues1.copy()
nearby_venues = nearby_venues.append(nearby_venues2)
nearby_venues = nearby_venues.append(nearby_venues3)

In [7]:
# check list and manually remove all non-restaurant data

nearby_venues['categories'].unique()

removal_list = ['Concert Hall', 'Opera House', 'Dance Studio',
                'Performing Arts Venue', 'Art Museum', 'Park',
                'Massage Studio', 'Music Venue', 'Bookstore', 'Clothing Store',
                'Boutique', 'Furniture/Home Store', 'Jazz Club',
                'Theater', 'Optical Shop', "Men's Store", 'Rock Club',
                'Gym / Fitness Center', 'Wine Shop', 'Indie Movie Theater',
                'Chocolate Shop', 'Dessert Shop', 'Recreation Center', 
                'Plaza', 'Hotel', 'Luggage Store', 'Farmers Market', 'Gym',
                'Jewelry Store', 'Furniture / Home Store', 'Butcher', 
                'Bakery', 'Marijuana Dispensary', 'Ice Cream Shop',
                'Comic Shop', 'Bagel Shop', 'Spa', 'Liquor Store', 'Bike Shop',
                'Yoga Studio', 'Pedestrian Plaza', 'Candy Store',
                'Park', 'Bookstore', 'Candy Store',  'Jazz Club', 'Art Gallery', 
                 'Supermarket', 'Museum', 'Boutique', 'Plaza', 'Building', 'Bakery',
                 'Historic Site', 'Ice Cream Shop', ' Concert Hall', 'Pharmacy', 
                 'Market', 'Movie Theater', 'Performing Arts Venue', 'Music Venue',
                 'Theater', 'Art Museum', 'Cheese Shop', 'Opera House',
                 'Pedestrian Plaza', 'School', 'Gift Shop', 'Athletics & Sports',
                 'Shoe Repair', 'General Entertainment', 'Stationery Store',
                 'Toy / Game Store', 'Brewery', 'Hotel', 'Theater', 'Music Venue', 'Business Service',
                 'Donut Shop', 'Liquor Store', 'Beer Store',
                 'Lounge', 'Plaza', 'Health Food Store', 'Concert Hall', 
                 'Lingerie Store', 'Gym', 'Mobile Phone Shop',
                 'Chocolate Shop', 'Ice Cream Shop', 'Hostel', 'Convenience Store', 
                 'Park', 'Farmers Market', 'Cosmetics Shop', 'Piano Bar',
                 'Nightclub', 'Massage Studio', 'Comedy Club', 'Concert Hall']

nearby_venues = nearby_venues[~nearby_venues['categories'].isin(removal_list)]

nearby_venues['categories'].unique()

array(['Ramen Restaurant', 'Beer Bar', 'Wine Bar', 'Coffee Shop',
       'Tiki Bar', 'Cocktail Bar', 'Italian Restaurant',
       'Sushi Restaurant', 'French Restaurant', 'Music School',
       'Poke Place', 'Food & Drink Shop',
       'Southern / Soul Food Restaurant', 'Event Space', 'Sandwich Place',
       'Thai Restaurant', 'Pizza Place', 'Beer Garden', 'Souvlaki Shop',
       'Juice Bar', 'American Restaurant', 'Mexican Restaurant',
       'New American Restaurant', 'Restaurant', 'Accessories Store',
       'German Restaurant', 'Café', 'Breakfast Spot', 'Speakeasy',
       'Udon Restaurant', 'Bar', 'Falafel Restaurant',
       'Filipino Restaurant', 'BBQ Joint', 'Japanese Restaurant',
       'Shopping Mall', 'Mediterranean Restaurant', 'Gastropub',
       'Latin American Restaurant', 'Cajun / Creole Restaurant',
       'Tea Room', 'Yoshoku Restaurant', 'Food Truck', 'Bubble Tea Shop',
       'High School', 'Train Station', 'Kids Store', 'Taco Place',
       'Seafood Restaurant', 'Brazilian Restaurant', 'Tattoo Parlor',
       'Pub', 'Hot Dog Joint', 'Empanada Restaurant', 'Burger Joint',
       'Vietnamese Restaurant', 'Shoe Store'], dtype=object)

In [8]:
# set up to pull the likes from the API based on venue ID

url_list = []
like_list = []
json_list = []

for i in list(nearby_venues.id):
    venue_url = 'https://api.foursquare.com/v2/venues/{}/likes?client_id={}&client_secret={}&v={}'.format(i, CLIENT_ID, CLIENT_SECRET, VERSION)
    url_list.append(venue_url)
for link in url_list:
    result = requests.get(link).json()
    likes = result['response']['likes']['count']
    like_list.append(likes)
print(like_list)


nearby_venues['likes'] = like_list
nearby_venues.head()

[351, 291, 132, 480, 457, 941, 298, 1114, 602, 120, 347, 152, 823, 375, 56, 77, 530, 301, 1184, 29, 439, 370, 18, 69, 801, 1074, 79, 73, 677, 50, 59, 19, 36, 309, 206, 609, 175, 47, 65, 74, 817, 314, 260, 288, 239, 243, 490, 113, 118, 731, 155, 218, 123, 80, 356, 340, 320, 138, 57, 585, 33, 84, 55, 92, 64, 22, 25, 78, 162, 105, 200, 48, 75, 120, 154, 395, 9, 327, 482, 357, 384, 32, 17, 58, 740, 21, 106, 269, 37, 140, 34, 111, 31, 24, 982, 23, 56, 9, 130, 12, 112, 235, 10, 39, 32, 28, 8, 12, 157, 76, 62, 34, 9, 150, 77, 131, 170, 207, 26, 143, 36, 41, 105, 36, 3, 64, 94, 10, 34, 65, 295, 18, 97, 7, 30, 8, 127, 30, 321, 119, 18, 104, 104, 196, 19, 22, 83, 33, 78, 525, 101, 31, 489, 140, 534, 35, 204, 479, 131, 5, 175, 20, 54, 27, 116, 22, 54, 48, 10, 175, 20]

,name,categories,lat,lng,id,city,likes
12,Nojo Ramen Tavern,Ramen Restaurant,37.776637,-122.421270,4d8eabc7d265236af9a71017,San Francisco,351
13,The Beer Hall,Beer Bar,37.776837,-122.417916,519fcb37498e91a13cb23d6b,San Francisco,291
14,Birba,Wine Bar,37.777750,-122.424159,551b7760498e1612b67f33f9,San Francisco,132
16,Philz Coffee,Coffee Shop,37.781433,-122.417073,5151a10ce4b06ae7735335db,San Francisco,480
17,Blue Bottle Coffee,Coffee Shop,37.776286,-122.416867,5560dbdb498e91a2bcde84f6,San Francisco,457

In [9]:
# this is really the raw dataset now so let us rename it something more appropriate

raw_dataset = nearby_venues
raw_dataset.head()

,name,categories,lat,lng,id,city,likes
12,Nojo Ramen Tavern,Ramen Restaurant,37.776637,-122.421270,4d8eabc7d265236af9a71017,San Francisco,351
13,The Beer Hall,Beer Bar,37.776837,-122.417916,519fcb37498e91a13cb23d6b,San Francisco,291
14,Birba,Wine Bar,37.777750,-122.424159,551b7760498e1612b67f33f9,San Francisco,132
16,Philz Coffee,Coffee Shop,37.781433,-122.417073,5151a10ce4b06ae7735335db,San Francisco,480
17,Blue Bottle Coffee,Coffee Shop,37.776286,-122.416867,5560dbdb498e91a2bcde84f6,San Francisco,457

## 2.2 Data Preparation

The data still needs some more processing before it is suitable for model training and testing. Mainly, the "categories" column contains too many different types of cuisines to allow a model to yield any meaningful results. However, the different types of natural cuisines have natural groupings based on conventionally accepted cultural groupings of cuisine. Broadly speaking, all of the different types of cuisine could be reclassified as European, Latin American, Asian, North American, drinking establishments (bars), or casual establishments such as coffee shops or ice cream parlours. We can implement manual classification as there really aren't that many different types of cuisines.

As this project will compare both linear and logistic regression, it makes sense to have "likes" as both a continuous and categorical (but ordinal) variable. In the case of turning into a categorical variable, we can bin the data based on percentiles and classify them into these ordinal percentile categories. I tried different ways of binning but in the end, splitting the sample into three different bins proved to yield the best classification results from a prediction standpoint.

As the last stage of data preparation, it is important to note that the regressors are categorical variables (3 different cities and 6 different categories of cusines). Hence, they require dummy variable encoding for meaningful analysis. We can accomplish this via one-hot encoding.

In [10]:
# inspecting the raw dataset shows that there may be too many different types of cuisines
raw_dataset['categories'].unique()

array(['Ramen Restaurant', 'Beer Bar', 'Wine Bar', 'Coffee Shop',
       'Tiki Bar', 'Cocktail Bar', 'Italian Restaurant',
       'Sushi Restaurant', 'French Restaurant', 'Music School',
       'Poke Place', 'Food & Drink Shop',
       'Southern / Soul Food Restaurant', 'Event Space', 'Sandwich Place',
       'Thai Restaurant', 'Pizza Place', 'Beer Garden', 'Souvlaki Shop',
       'Juice Bar', 'American Restaurant', 'Mexican Restaurant',
       'New American Restaurant', 'Restaurant', 'Accessories Store',
       'German Restaurant', 'Café', 'Breakfast Spot', 'Speakeasy',
       'Udon Restaurant', 'Bar', 'Falafel Restaurant',
       'Filipino Restaurant', 'BBQ Joint', 'Japanese Restaurant',
       'Shopping Mall', 'Mediterranean Restaurant', 'Gastropub',
       'Latin American Restaurant', 'Cajun / Creole Restaurant',
       'Tea Room', 'Yoshoku Restaurant', 'Food Truck', 'Bubble Tea Shop',
       'High School', 'Train Station', 'Kids Store', 'Taco Place',
       'Seafood Restaurant', 'Brazilian Restaurant', 'Tattoo Parlor',
       'Pub', 'Hot Dog Joint', 'Empanada Restaurant', 'Burger Joint',
       'Vietnamese Restaurant', 'Shoe Store'], dtype=object)

In [11]:
# we can group some cuisines together to make a better categorical variable

euro = ['French Restaurant', 'Scandinavian Restaurant', 'Souvlaki Shop', 
       'Mediterranean Restaurant', 'Italian Restaurant', 'Pizza Place']

latino = ['Mexican Restaurant', 'Latin American Restaurant', 
          'Brazilian Restaurant', 'Taco Place']

bar = ['Beer Bar', 'Cocktail Bar', 'Tiki Bar', 'Wine Bar', 'Hotel Bar',
       'Beer Garden', 'Speakeasy', 'Brewery', 'Pub', 'Bar', 'Gastropub',
       'Hookah Bar']

asian = ['Ramen Restaurant', 'Sushi Restaurant', 'Vietnamese Restaurant',
         'Thai Restaurant', 'Poke Place', 'Indian Restaurant', 
         'Japanese Curry Restaurant', 'Japanese Restaurant', 
         'Indonesian Restaurant', 'Udon Restaurant', 'Noodle House',
         'Falafel Restaurant', 'Filipino Restaurant', 'Turkish Restaurant',
         'Yoshoku Restaurant']

casual = ['Coffee Shop', 'Café', 'Sandwich Place', 'Food Truck',
          'Juice Bar', 'Frozen Yogurt Shop', 'Deli / Bodega', 'Dessert Shop',
          'Hot Dog Joint', 'Burger Joint', 'Breakfast Spot', 
          'Fondue Restaurant']

american = ['Southern / Soul Food Restaurant', 'Food & Drink Shop', 
            'Restaurant', 'American Restaurant', 'BBQ Joint', 
            'Theme Restaurant', 'New American Restaurant',
            'Vegetarian / Vegan Restaurant', 'Seafood Restaurant']

def conditions(s):
    if s['categories'] in euro:
        return 'euro'
    if s['categories'] in latino:
        return 'latino'
    if s['categories'] in asian:
        return 'asian'
    if s['categories'] in casual:
        return 'casual'
    if s['categories'] in american:
        return 'american'
    if s['categories'] in bar:
        return 'bar'


raw_dataset['categories_classified']=raw_dataset.apply(conditions, axis=1)
raw_dataset

,name,categories,lat,lng,id,city,likes,categories_classified
12,Nojo Ramen Tavern,Ramen Restaurant,37.776637,-122.421270,4d8eabc7d265236af9a71017,San Francisco,351,asian
13,The Beer Hall,Beer Bar,37.776837,-122.417916,519fcb37498e91a13cb23d6b,San Francisco,291,bar
14,Birba,Wine Bar,37.777750,-122.424159,551b7760498e1612b67f33f9,San Francisco,132,bar
16,Philz Coffee,Coffee Shop,37.781433,-122.417073,5151a10ce4b06ae7735335db,San Francisco,480,casual
17,Blue Bottle Coffee,Coffee Shop,37.776286,-122.416867,5560dbdb498e91a2bcde84f6,San Francisco,457,casual
18,Blue Bottle Coffee,Coffee Shop,37.776430,-122.423224,43d3901ef964a5201f2e1fe3,San Francisco,941,casual
19,Fig & Thistle Wine Bar,Wine Bar,37.777256,-122.423365,51aad1ee498e9bb839540dc7,San Francisco,298,bar
20,Smuggler's Cove,Tiki Bar,37.779386,-122.423422,4afe6db4f964a520682f22e3,San Francisco,1114,bar
21,Whitechapel,Cocktail Bar,37.782230,-122.418884,55df9e27498ef4c72ac83a77,San Francisco,602,bar
23,Linden Room,Cocktail Bar,37.776503,-122.422794,57b3c7c8498e9b9e08349941,San Francisco,120,bar
29,a Mano,Italian Restaurant,37.776917,-122.423856,5907aa1c178a2a76066e0f59,San Francisco,347,euro
30,Robin,Sushi Restaurant,37.779127,-122.423378,5955a2f275cb8c11484ffc5f,San Francisco,152,asian
31,Ritual Coffee Roasters,Coffee Shop,37.776476,-122.424281,4dd94350e4cd37c893d8146f,San Francisco,823,casual
32,Monsieur Benjamin,French Restaurant,37.777478,-122.423131,53b4dd52498eef48c82d89a5,San Francisco,375,euro
33,San Francisco Conservatory of Music,Music School,37.775489,-122.420381,49f4ee82f964a520796b1fe3,San Francisco,56,None
35,Poké Bar,Poke Place,37.776507,-122.417254,5755cbd5498e79290f67dd57,San Francisco,77,asian
37,The Market,Food & Drink Shop,37.776560,-122.417275,547cd07d498ef3265ffc5a75,San Francisco,530,american
38,Anina,Cocktail Bar,37.776713,-122.424273,58c235d16ad5a1406910da40,San Francisco,301,bar
40,Brenda's French Soul Food,Southern / Soul Food Restaurant,37.782896,-122.418897,49f356f8f964a5208a6a1fe3,San Francisco,1184,american
41,Proxy SF,Event Space,37.776501,-122.424245,4e9a188d5503cfce741c285d,San Francisco,29,None
43,Saigon Sandwich,Sandwich Place,37.783084,-122.417650,43eb7d31f964a520392f1fe3,San Francisco,439,casual
45,Lers Ros Thai,Thai Restaurant,37.777045,-122.421671,4ebd985c6c257f09ae0c188e,San Francisco,370,asian
46,Del Popolo Truck,Pizza Place,37.776583,-122.424263,5b12f114088158002cd23509,San Francisco,18,euro
47,Hinata,Sushi Restaurant,37.783090,-122.420732,584a0d7b349355671db7eab2,San Francisco,69,asian
48,Biergarten,Beer Garden,37.776013,-122.424247,4dd7e48fd22d38ef42f35bd8,San Francisco,801,bar
49,Souvla,Souvlaki Shop,37.776568,-122.424957,533cc33f498e604ebad95d8c,San Francisco,1074,euro
50,George and Lennie,Coffee Shop,37.781701,-122.415213,55da2db5498eb79ab95580cb,San Francisco,79,casual
52,Juice Shop,Juice Bar,37.776462,-122.424302,5205771c11d29e527c11fccd,San Francisco,73,casual
54,Absinthe Brasserie & Bar,French Restaurant,37.777009,-122.423004,43dc103ef964a520992e1fe3,San Francisco,677,euro
58,Ales Unlimited: Beer Basement,Beer Bar,37.782751,-122.415656,57412b42498ee7dadefaa071,San Francisco,50,bar
64,Project Juice,Juice Bar,37.777035,-122.422375,56227db5498efb1e8f33ef41,San Francisco,59,casual
66,San Francisco Wine & Cheese,Wine Bar,37.774782,-122.422852,5a169ad189e4903124fb896d,San Francisco,19,bar
67,Morty's Delicatessen,American Restaurant,37.781710,-122.415243,49d66c4ef964a520c95c1fe3,San Francisco,36,american
69,Papito Hayes,Mexican Restaurant,37.776713,-122.423459,537a5895498eaeb3ef2970cb,San Francisco,309,latino
73,RT Rotisserie,New American Restaurant,37.775204,-122.421061,591e5b7135dfa71049910b5b,San Francisco,206,american
76,Rich Table,New American Restaurant,37.774891,-122.422736,500088f7d63e64b62bc19e6e,San Francisco,609,american
77,Coffee Cultures,Coffee Shop,37.776089,-122.414717,56e73a8d498e1963764d2dcf,San Francisco,175,casual
80,Gioia Pizzeria,Pizza Place,37.776328,-122.425859,5cfaca87a2c00b002bd3242e,San Francisco,47,euro
82,Nightbird,Restaurant,37.776541,-122.422904,57b3c4c6cd10588ecc2e71e2,San Francisco,65,american
83,Timbuk2,Accessories Store,37.776636,-122.424854,4a87bb7cf964a520e00420e3,San Francisco,74,None
85,Suppenküche,German Restaurant,37.776324,-122.426382,42c5d900f964a520d5251fe3,San Francisco,817,None
86,Otoro Sushi,Sushi Restaurant,37.774974,-122.422900,4a45ae19f964a52073a81fe3,San Francisco,314,asian
87,Petit Crenn,French Restaurant,37.776344,-122.426455,55c29cba498e3e3e7a929bb7,San Francisco,260,euro
88,20th Century Cafe,Café,37.774903,-122.422434,51d9ade3498eeedbc8f06c0a,San Francisco,288,casual
89,Hotel Biron,Wine Bar,37.773504,-122.422110,43fb0c0ef964a520df2f1fe3,San Francisco,239,bar
90,Little Gem,Café,37.777831,-122.423282,5671c6d5498e5a1f5e444400,San Francisco,243,casual
93,Domo Sushi,Sushi Restaurant,37.775951,-122.426151,49ce86fff964a520515a1fe3,San Francisco,490,asian
94,City Beer Store,Beer Bar,37.778493,-122.412244,5b83612295a722002ccd6e80,San Francisco,113,bar
95,The Lunchpad,Sandwich Place,37.776490,-122.425896,51685f7de4b08ce8b5293934,San Francisco,118,casual
98,Lers Ros Thai,Thai Restaurant,37.784759,-122.417811,49dd8602f964a52018601fe3,San Francisco,731,asian
99,Rusty's Southern,Southern / Soul Food Restaurant,37.784200,-122.418518,552043bc498ea443ae08a883,San Francisco,155,american
1,Redbird,American Restaurant,34.050666,-118.244068,54938133498ed65f02e8c4ba,Los Angeles,218,american
5,JiST Cafe,Breakfast Spot,34.050908,-118.240436,51dccd46498e4f9ac4865270,Los Angeles,123,casual
6,Birds & Bees,Speakeasy,34.052090,-118.247376,5873fafb5e789611577ee395,Los Angeles,80,bar
9,Marugame Monzo,Udon Restaurant,34.049807,-118.240202,5143f2d7e4b039102cf9793f,Los Angeles,356,asian
13,Cafe Demitasse,Coffee Shop,34.049668,-118.241696,4e2071738130e92fc6a3f821,Los Angeles,340,casual
17,Far Bar,Bar,34.049591,-118.239739,4a562876f964a52096b41fe3,Los Angeles,320,bar
18,Blue Bottle Coffee,Coffee Shop,34.050881,-118.247952,58680bee9c439d2cc839d367,Los Angeles,138,casual
24,Starbucks,Coffee Shop,34.058780,-118.240249,53487060498e5e04e7503d6c,Los Angeles,57,casual
27,Daikokuya,Ramen Restaurant,34.049914,-118.240095,4127e200f964a520540c1fe3,Los Angeles,585,asian
30,Tilt Coffee,Coffee Shop,34.048258,-118.246359,5856f788158b966de017c324,Los Angeles,33,casual
31,Kismet Falafel,Falafel Restaurant,34.050791,-118.249007,554a75cc498eccd15edaf98e,Los Angeles,84,asian
32,Sari Sari Store LA,Filipino Restaurant,34.051065,-118.249390,5956f0d0f5e9d7161f043456,Los Angeles,55,asian
37,Spring Street SmokeHouse,BBQ Joint,34.058379,-118.238509,4a7c7f3df964a520cbec1fe3,Los Angeles,92,american
39,Mitsuru Cafe,Japanese Restaurant,34.048959,-118.240001,4b3e9810f964a520789f25e3,Los Angeles,64,asian
40,Rakkan Ramen,Ramen Restaurant,34.049447,-118.239528,596448501987ec3cfd0626f0,Los Angeles,22,asian
41,La Noche Buena,Mexican Restaurant,34.057186,-118.238181,4ab99509f964a520f27f20e3,Los Angeles,25,latino
42,Patina Restaurant,French Restaurant,34.054712,-118.249590,4ad01a5af964a52095d720e3,Los Angeles,78,euro
43,Wolf & Crane Bar,Bar,34.047942,-118.239650,51aee770454a09a5e4e3b2f9,Los Angeles,162,bar
44,Hama Sushi,Sushi Restaurant,34.048527,-118.240500,49d97513f964a520395e1fe3,Los Angeles,105,asian
45,Maccheroni Republic,Italian Restaurant,34.050020,-118.248656,50d223c5e4b00439552865de,Los Angeles,200,euro
50,Little Tokyo Mall,Shopping Mall,34.049012,-118.240547,4cc4b82401fb236aaf9eadba,Los Angeles,48,None
51,Komasa,Japanese Restaurant,34.048499,-118.240424,4ad54f8cf964a520c70221e3,Los Angeles,75,asian
52,Cielito Lindo,Mexican Restaurant,34.058044,-118.237457,4b53787df964a5208b9e27e3,Los Angeles,120,latino
54,Spitz,Mediterranean Restaurant,34.048144,-118.239962,49ef5a6ef964a520a6681fe3,Los Angeles,154,euro
55,Shin-Sen-Gumi,Ramen Restaurant,34.048187,-118.239152,4e5b046a227188671508b714,Los Angeles,395,asian
56,Prime Pizza,Pizza Place,34.048063,-118.239393,5a14c1f9628c832160a43648,Los Angeles,9,euro
57,KazuNori: The Original Hand Roll Bar,Sushi Restaurant,34.047716,-118.247452,53d06bba498e6c801ea9816e,Los Angeles,327,asian
59,Bäco Mercat,Gastropub,34.047854,-118.247413,4eb4d3d31081376a2c1edadf,Los Angeles,482,bar
60,Bar Amá,Mexican Restaurant,34.048523,-118.248076,50c92ed6e4b08539f9ff721c,Los Angeles,357,latino
61,G&B Coffee,Coffee Shop,34.051006,-118.249356,51a8d473498ea68ee462260c,Los Angeles,384,casual
62,Zencu Sushi & Grill,Sushi Restaurant,34.049178,-118.240654,4a07bb56f964a52098731fe3,Los Angeles,32,asian
64,Sushi Zo,Sushi Restaurant,34.048148,-118.247188,522fe77511d2e9bbd1856537,Los Angeles,17,asian
65,Sarita's Pupuseria,Latin American Restaurant,34.050735,-118.248875,4aef41e4f964a520fcd621e3,Los Angeles,58,latino
67,Eggslut,Breakfast Spot,34.050635,-118.248678,527bf41911d2ff4cca3e912e,Los Angeles,740,casual
68,Chinchikurin Hiroshima Okonomiyaki,Japanese Restaurant,34.049464,-118.239715,5aa19448f96b2c6dc60bfaf2,Los Angeles,21,asian
69,Oomasa,Sushi Restaurant,34.049294,-118.239678,412d2800f964a520d80c1fe3,Los Angeles,106,asian
70,Otium,New American Restaurant,34.054312,-118.251214,563ac687cd101c7dff9cd41b,Los Angeles,269,american
72,Weller Court,Shopping Mall,34.050068,-118.242135,4bb796bd1261d13ab986e798,Los Angeles,37,None
73,Little Jewel of New Orleans,Cajun / Creole Restaurant,34.060036,-118.238260,53f105e5498e9e63662731bd,Los Angeles,140,None
74,Chado Tea Room,Tea Room,34.049219,-118.238580,4b77488cf964a520a88e2ee3,Los Angeles,34,None
76,Suehiro Cafe,Yoshoku Restaurant,34.049717,-118.239989,4a3c745df964a5208ea11fe3,Los Angeles,111,asian
77,Bar Clacson,Bar,34.049921,-118.249304,5865a033424f935d0b310727,Los Angeles,31,bar
79,Free Range LA,Food Truck,34.048229,-118.238097,5117f31ee4b03863cbbc1e7a,Los Angeles,24,casual
80,Philippe The Original,Sandwich Place,34.059622,-118.237013,4470358df964a52089331fe3,Los Angeles,982,casual
81,TOT / Teishokuya of Tokyo,Japanese Restaurant,34.048567,-118.240549,4f6dab16e4b09530ae838613,Los Angeles,23,asian
82,Mendocino Farms,Sandwich Place,34.052485,-118.251422,4a15b32ff964a520bb781fe3,Los Angeles,56,casual
84,Starbucks,Coffee Shop,34.049518,-118.241908,57fd4578498e20e69bc98c2a,Los Angeles,9,casual
85,Men Oh Tokushima Ramen,Ramen Restaurant,34.047238,-118.238668,506b47e3e4b010161f10b560,Los Angeles,130,asian
86,Mitsuru Sushi and Grill,Sushi Restaurant,34.050066,-118.240620,4b5b6561f964a520b2fa28e3,Los Angeles,12,asian
88,Twinkle Brown Sugar,Bubble Tea Shop,34.048207,-118.239313,4f418d14e4b0e408260f5cb8,Los Angeles,112,None
89,Sushi Gen,Sushi Restaurant,34.046849,-118.238520,4a087129f964a520c7731fe3,Los Angeles,235,asian
90,Ramón C. Cortines School of Visual and Perform...,High School,34.059485,-118.244042,4fc519a0e4b0452621553472,Los Angeles,10,None
91,Angels Flight - Upper Station,Train Station,34.051561,-118.250644,50a00eaf19a918cf99a8f624,Los Angeles,39,None
92,Hakata Ikkousha,Ramen Restaurant,34.047891,-118.239578,5932386367af3a528de0ad76,Los Angeles,32,asian
97,Midori Matcha,Food & Drink Shop,34.050011,-118.242124,5869aa300037eb49446d5351,Los Angeles,28,american
98,Monkey Pants,Kids Store,34.049009,-118.240494,508b4d36e4b0ad933b7a49d8,Los Angeles,8,None
99,Bicycle Coffee,Coffee Shop,34.048184,-118.240115,5b5a3567c03635002c97f1a1,Los Angeles,12,casual
1,Tender Greens,New American Restaurant,32.716082,-117.163925,51d0c254498e603aabbc5bae,San Diego,157,american
3,Grant Grill,American Restaurant,32.716125,-117.161084,40e0b100f964a52030021fe3,San Diego,76,american
5,WestBean Coffee Roasters,Coffee Shop,32.715736,-117.162460,54dcf93e498e72ab49cd0ba8,San Diego,62,casual
6,Dobson's Bar & Restaurant,American Restaurant,32.715400,-117.162741,40e0b100f964a52008021fe3,San Diego,34,american
8,Le Fontainbleau - The Westgate Hotel,French Restaurant,32.716267,-117.162452,4e4c4687bd413c4cc668273f,San Diego,9,euro
9,The Local Eatery and Drinking Hole,Bar,32.716501,-117.160933,4165d880f964a520791d1fe3,San Diego,150,bar
12,The Taco Stand Downtown,Taco Place,32.717749,-117.158497,568daf60498eaf94b8afbc5d,San Diego,77,latino
14,The Crab Hut,Seafood Restaurant,32.715802,-117.159871,4c48d7c7b5eec9b6e945efa3,San Diego,131,american
15,Rei Do Gado,Brazilian Restaurant,32.715202,-117.160940,4b933ab9f964a5204d3c34e3,San Diego,170,latino
17,Vin de Syrah Wine Parlor,Wine Bar,32.714723,-117.160040,4a3dd4d2f964a520b3a21fe3,San Diego,207,bar
21,Chef Miguel's Deli,Sandwich Place,32.716500,-117.158690,4bbce75f8a4fb713dc533c9d,San Diego,26,casual
22,Sushi 2,Sushi Restaurant,32.715731,-117.163122,4a9887fdf964a520882c20e3,San Diego,143,asian
23,Starbucks,Coffee Shop,32.715306,-117.161453,52869068498e3289da674749,San Diego,36,casual
25,Cocina 35 Old School Mexican,Mexican Restaurant,32.720279,-117.159258,556cd86c498e348960e5a64f,San Diego,41,latino
26,The Kebab Shop,Falafel Restaurant,32.720824,-117.165654,4f35d936e4b0a1f1952a21aa,San Diego,105,asian
28,Operacaffe,Italian Restaurant,32.714041,-117.160996,4abd87d6f964a520dc8a20e3,San Diego,36,euro
29,Superfly Tattoo & Body Piercing,Tattoo Parlor,32.715811,-117.159834,4b9da40ef964a520beb736e3,San Diego,3,None
34,Osetra the Fishhouse,Seafood Restaurant,32.714777,-117.160314,4bf8834db182c9b636ad775a,San Diego,64,american
35,Chipotle Mexican Grill,Mexican Restaurant,32.715021,-117.164296,4ee915df2c5b49765f15860b,San Diego,94,latino
36,Achilles Coffee Outdoor Cafe,Café,32.717678,-117.157378,59d9458f916bc1155f05ce54,San Diego,10,casual
38,Full Moon Sushi and Kitchen Bar,Sushi Restaurant,32.715117,-117.160260,5393d0e8498e57e15686179c,San Diego,34,asian
46,Stone Company Store,Pub,32.717810,-117.169327,52785f0f11d25028a33cfc74,San Diego,65,bar
47,Queenstown Public House,New American Restaurant,32.721800,-117.167297,4f57df61e4b0b09e31372326,San Diego,295,american
50,City Pizzeria,Pizza Place,32.717746,-117.159197,4bce5a44ef10952130128486,San Diego,18,euro
54,Buca di Beppo,Italian Restaurant,32.712895,-117.159095,44eb7237f964a520cb371fe3,San Diego,97,euro
57,SoleLuna Cafe,Café,32.720016,-117.158305,4e13825762e14518a91d8b22,San Diego,7,casual
58,Dog Haus Biergarten,Hot Dog Joint,32.715529,-117.156307,5734add2498e90770a893def,San Diego,30,casual
60,Empanada Kitchen,Empanada Restaurant,32.716517,-117.157137,5a7cc0631953f35cd30ab191,San Diego,8,None
61,Breakfast Republic,Breakfast Spot,32.712501,-117.158175,5895f33b3bd4ab768a550a90,San Diego,127,casual
62,Salvatore's Cucina Italiana,Italian Restaurant,32.712613,-117.164786,4b9328a6f964a520613834e3,San Diego,30,euro
63,Hodad's Downtown,Burger Joint,32.715552,-117.155845,4b3be509f964a520d27d25e3,San Diego,321,casual
65,Spike Africa's Fresh Fish Bar & Grill,Seafood Restaurant,32.715534,-117.160880,50e8ece5e4b044bde4882ff1,San Diego,119,american
66,Copa Vida,Coffee Shop,32.715697,-117.168531,5892465a9398ab157a750b84,San Diego,18,casual
67,Craft & Commerce,Gastropub,32.720875,-117.168964,57c8db30498e75e3ba174353,San Diego,104,bar
68,Isola Pizza Bar,Italian Restaurant,32.721200,-117.168336,4f887912e4b0b1c4aeda18f9,San Diego,104,euro
69,Noble Experiment,Speakeasy,32.712412,-117.157602,4b764958f964a520ba462ee3,San Diego,196,bar
71,Old Gallery Coffee House,Coffee Shop,32.717758,-117.158601,4b6223f0f964a52019382ae3,San Diego,19,casual
72,Achilles Coffee Roasters,Coffee Shop,32.719710,-117.158246,5734ae4bcd10494d763052fc,San Diego,22,casual
73,Lofty Coffee Little Italy Cafe And Bakery,Café,32.722115,-117.167341,589cbdd52c55ec4c239a9360,San Diego,83,casual
74,Ramen Yamadaya,Ramen Restaurant,32.715721,-117.159623,564ff470498ee3d910f427e5,San Diego,33,asian
75,False Idol,Tiki Bar,32.720878,-117.168870,57cca899498e646cd72b5539,San Diego,78,bar
76,Ironside Fish & Oyster,Seafood Restaurant,32.722721,-117.168453,5343742b11d22b61cbaab411,San Diego,525,american
78,El Dorado Cocktail Lounge,Cocktail Bar,32.715865,-117.154983,491be395f964a52073521fe3,San Diego,101,bar
79,Tacos El Cabron,Mexican Restaurant,32.710852,-117.161130,5a0e148fd0a1494ae8bd06bb,San Diego,31,latino
80,Richard Walker's Pancake House San Diego,Breakfast Spot,32.711029,-117.164882,46499c1cf964a520aa461fe3,San Diego,489,casual
81,Burger Lounge Little Italy,Burger Joint,32.722158,-117.168342,4a6bed30f964a52044d01fe3,San Diego,140,casual
82,Barleymash,Bar,32.711608,-117.160181,4ee7e3a102d5895bd6b461e0,San Diego,534,bar
83,Pho Xpress,Vietnamese Restaurant,32.717299,-117.159161,4b64e4c3f964a52004d82ae3,San Diego,35,asian
84,Fogo de Chão,Brazilian Restaurant,32.712315,-117.159506,51df2bc7920951789f296f3f,San Diego,204,latino
85,La Puerta,Mexican Restaurant,32.711093,-117.161181,4a2f333df964a520b7981fe3,San Diego,479,latino
86,Taka Sushi,Sushi Restaurant,32.711171,-117.159939,4a66bb44f964a520d2c81fe3,San Diego,131,asian
88,Vans,Shoe Store,32.713673,-117.163174,4ba7b01bf964a520d2a939e3,San Diego,5,None
89,Pokez Mexican Restaurant,Mexican Restaurant,32.714574,-117.155761,44e07ae1f964a520fa361fe3,San Diego,175,latino
90,Time Out Sports Tavern,American Restaurant,32.715840,-117.158586,4d360eebfe972c0f49a99ab3,San Diego,20,american
91,Tajima Ramen East Village,Ramen Restaurant,32.714553,-117.156398,5680b03a498e78a8fe2287dc,San Diego,54,asian
92,Vitality Tap,Juice Bar,32.712377,-117.163849,51956237498e5b3fcce3af52,San Diego,27,casual
93,Buon Appetito Restaurant,Italian Restaurant,32.722400,-117.168073,42a8d800f964a5201e251fe3,San Diego,116,euro
94,SoleLuna Cafe,Italian Restaurant,32.719913,-117.158480,4a2f0206f964a52096981fe3,San Diego,22,euro
95,Indigo Grill,American Restaurant,32.721737,-117.168237,41575800f964a520341d1fe3,San Diego,54,american
96,Sorrento Ristorante And Pizzeria,Italian Restaurant,32.722530,-117.168560,559f3d4b498e8674883281b4,San Diego,48,euro
97,Not Not Tacos,Taco Place,32.723081,-117.167730,5b51614c0a08ab002c39e193,San Diego,10,latino
98,The Lion's Share,Bar,32.711905,-117.169035,4ea9de56f9f45048e718d81f,San Diego,175,bar
99,Spill The Beans Coffee And Bagel,Coffee Shop,32.711511,-117.159538,59970ecdbfc6d003052f6210,San Diego,20,casual

In [12]:
# double check to make sure categories_classified has been created correctly

pd.crosstab(index=raw_dataset["categories_classified"],
            columns="count")

col_0                  count
categories_classified
american                  21
asian                     35
bar                       26
casual                    40
euro                      20
latino                    14

In [13]:
# classify the likes into different ranking levels
# lets first see where to bin the data
# we can try different ways of binning the data, I find it yields substantially different results

# print(np.percentile(raw_dataset['likes'], 20))
# print(np.percentile(raw_dataset['likes'], 40))
# print(np.percentile(raw_dataset['likes'], 60))
# print(np.percentile(raw_dataset['likes'], 80))


print(np.percentile(raw_dataset['likes'], 33))
print(np.percentile(raw_dataset['likes'], 66))


# print(np.percentile(raw_dataset['likes'], 50))

55.1
163.60000000000002

In [14]:
# create a function to bin for us

# def rankings(s):
#     if s['likes']<=34:
#         return 1
#     if s['likes']<=78:
#         return 2
#     if s['likes']<=154.6:
#         return 3
#     if s['likes']<=326.4:
#         return 4
#     if s['likes']>326.4:
#         return 5

def rankings(s):
    if s['likes']<=62:
        return 1
    if s['likes']<=193.22:
        return 2
    if s['likes']>193.22:
        return 3
    
    
# def rankings(s):
#     if s['likes']<=111.5:
#         return 0
#     if s['likes']>111.5:
#         return 1

raw_dataset['ranking']=raw_dataset.apply(rankings, axis=1)
raw_dataset

,name,categories,lat,lng,id,city,likes,categories_classified,ranking
12,Nojo Ramen Tavern,Ramen Restaurant,37.776637,-122.421270,4d8eabc7d265236af9a71017,San Francisco,351,asian,3
13,The Beer Hall,Beer Bar,37.776837,-122.417916,519fcb37498e91a13cb23d6b,San Francisco,291,bar,3
14,Birba,Wine Bar,37.777750,-122.424159,551b7760498e1612b67f33f9,San Francisco,132,bar,2
16,Philz Coffee,Coffee Shop,37.781433,-122.417073,5151a10ce4b06ae7735335db,San Francisco,480,casual,3
17,Blue Bottle Coffee,Coffee Shop,37.776286,-122.416867,5560dbdb498e91a2bcde84f6,San Francisco,457,casual,3
18,Blue Bottle Coffee,Coffee Shop,37.776430,-122.423224,43d3901ef964a5201f2e1fe3,San Francisco,941,casual,3
19,Fig & Thistle Wine Bar,Wine Bar,37.777256,-122.423365,51aad1ee498e9bb839540dc7,San Francisco,298,bar,3
20,Smuggler's Cove,Tiki Bar,37.779386,-122.423422,4afe6db4f964a520682f22e3,San Francisco,1114,bar,3
21,Whitechapel,Cocktail Bar,37.782230,-122.418884,55df9e27498ef4c72ac83a77,San Francisco,602,bar,3
23,Linden Room,Cocktail Bar,37.776503,-122.422794,57b3c7c8498e9b9e08349941,San Francisco,120,bar,2
29,a Mano,Italian Restaurant,37.776917,-122.423856,5907aa1c178a2a76066e0f59,San Francisco,347,euro,3
30,Robin,Sushi Restaurant,37.779127,-122.423378,5955a2f275cb8c11484ffc5f,San Francisco,152,asian,2
31,Ritual Coffee Roasters,Coffee Shop,37.776476,-122.424281,4dd94350e4cd37c893d8146f,San Francisco,823,casual,3
32,Monsieur Benjamin,French Restaurant,37.777478,-122.423131,53b4dd52498eef48c82d89a5,San Francisco,375,euro,3
33,San Francisco Conservatory of Music,Music School,37.775489,-122.420381,49f4ee82f964a520796b1fe3,San Francisco,56,None,1
35,Poké Bar,Poke Place,37.776507,-122.417254,5755cbd5498e79290f67dd57,San Francisco,77,asian,2
37,The Market,Food & Drink Shop,37.776560,-122.417275,547cd07d498ef3265ffc5a75,San Francisco,530,american,3
38,Anina,Cocktail Bar,37.776713,-122.424273,58c235d16ad5a1406910da40,San Francisco,301,bar,3
40,Brenda's French Soul Food,Southern / Soul Food Restaurant,37.782896,-122.418897,49f356f8f964a5208a6a1fe3,San Francisco,1184,american,3
41,Proxy SF,Event Space,37.776501,-122.424245,4e9a188d5503cfce741c285d,San Francisco,29,None,1
43,Saigon Sandwich,Sandwich Place,37.783084,-122.417650,43eb7d31f964a520392f1fe3,San Francisco,439,casual,3
45,Lers Ros Thai,Thai Restaurant,37.777045,-122.421671,4ebd985c6c257f09ae0c188e,San Francisco,370,asian,3
46,Del Popolo Truck,Pizza Place,37.776583,-122.424263,5b12f114088158002cd23509,San Francisco,18,euro,1
47,Hinata,Sushi Restaurant,37.783090,-122.420732,584a0d7b349355671db7eab2,San Francisco,69,asian,2
48,Biergarten,Beer Garden,37.776013,-122.424247,4dd7e48fd22d38ef42f35bd8,San Francisco,801,bar,3
49,Souvla,Souvlaki Shop,37.776568,-122.424957,533cc33f498e604ebad95d8c,San Francisco,1074,euro,3
50,George and Lennie,Coffee Shop,37.781701,-122.415213,55da2db5498eb79ab95580cb,San Francisco,79,casual,2
52,Juice Shop,Juice Bar,37.776462,-122.424302,5205771c11d29e527c11fccd,San Francisco,73,casual,2
54,Absinthe Brasserie & Bar,French Restaurant,37.777009,-122.423004,43dc103ef964a520992e1fe3,San Francisco,677,euro,3
58,Ales Unlimited: Beer Basement,Beer Bar,37.782751,-122.415656,57412b42498ee7dadefaa071,San Francisco,50,bar,1
64,Project Juice,Juice Bar,37.777035,-122.422375,56227db5498efb1e8f33ef41,San Francisco,59,casual,1
66,San Francisco Wine & Cheese,Wine Bar,37.774782,-122.422852,5a169ad189e4903124fb896d,San Francisco,19,bar,1
67,Morty's Delicatessen,American Restaurant,37.781710,-122.415243,49d66c4ef964a520c95c1fe3,San Francisco,36,american,1
69,Papito Hayes,Mexican Restaurant,37.776713,-122.423459,537a5895498eaeb3ef2970cb,San Francisco,309,latino,3
73,RT Rotisserie,New American Restaurant,37.775204,-122.421061,591e5b7135dfa71049910b5b,San Francisco,206,american,3
76,Rich Table,New American Restaurant,37.774891,-122.422736,500088f7d63e64b62bc19e6e,San Francisco,609,american,3
77,Coffee Cultures,Coffee Shop,37.776089,-122.414717,56e73a8d498e1963764d2dcf,San Francisco,175,casual,2
80,Gioia Pizzeria,Pizza Place,37.776328,-122.425859,5cfaca87a2c00b002bd3242e,San Francisco,47,euro,1
82,Nightbird,Restaurant,37.776541,-122.422904,57b3c4c6cd10588ecc2e71e2,San Francisco,65,american,2
83,Timbuk2,Accessories Store,37.776636,-122.424854,4a87bb7cf964a520e00420e3,San Francisco,74,None,2
85,Suppenküche,German Restaurant,37.776324,-122.426382,42c5d900f964a520d5251fe3,San Francisco,817,None,3
86,Otoro Sushi,Sushi Restaurant,37.774974,-122.422900,4a45ae19f964a52073a81fe3,San Francisco,314,asian,3
87,Petit Crenn,French Restaurant,37.776344,-122.426455,55c29cba498e3e3e7a929bb7,San Francisco,260,euro,3
88,20th Century Cafe,Café,37.774903,-122.422434,51d9ade3498eeedbc8f06c0a,San Francisco,288,casual,3
89,Hotel Biron,Wine Bar,37.773504,-122.422110,43fb0c0ef964a520df2f1fe3,San Francisco,239,bar,3
90,Little Gem,Café,37.777831,-122.423282,5671c6d5498e5a1f5e444400,San Francisco,243,casual,3
93,Domo Sushi,Sushi Restaurant,37.775951,-122.426151,49ce86fff964a520515a1fe3,San Francisco,490,asian,3
94,City Beer Store,Beer Bar,37.778493,-122.412244,5b83612295a722002ccd6e80,San Francisco,113,bar,2
95,The Lunchpad,Sandwich Place,37.776490,-122.425896,51685f7de4b08ce8b5293934,San Francisco,118,casual,2
98,Lers Ros Thai,Thai Restaurant,37.784759,-122.417811,49dd8602f964a52018601fe3,San Francisco,731,asian,3
99,Rusty's Southern,Southern / Soul Food Restaurant,37.784200,-122.418518,552043bc498ea443ae08a883,San Francisco,155,american,2
1,Redbird,American Restaurant,34.050666,-118.244068,54938133498ed65f02e8c4ba,Los Angeles,218,american,3
5,JiST Cafe,Breakfast Spot,34.050908,-118.240436,51dccd46498e4f9ac4865270,Los Angeles,123,casual,2
6,Birds & Bees,Speakeasy,34.052090,-118.247376,5873fafb5e789611577ee395,Los Angeles,80,bar,2
9,Marugame Monzo,Udon Restaurant,34.049807,-118.240202,5143f2d7e4b039102cf9793f,Los Angeles,356,asian,3
13,Cafe Demitasse,Coffee Shop,34.049668,-118.241696,4e2071738130e92fc6a3f821,Los Angeles,340,casual,3
17,Far Bar,Bar,34.049591,-118.239739,4a562876f964a52096b41fe3,Los Angeles,320,bar,3
18,Blue Bottle Coffee,Coffee Shop,34.050881,-118.247952,58680bee9c439d2cc839d367,Los Angeles,138,casual,2
24,Starbucks,Coffee Shop,34.058780,-118.240249,53487060498e5e04e7503d6c,Los Angeles,57,casual,1
27,Daikokuya,Ramen Restaurant,34.049914,-118.240095,4127e200f964a520540c1fe3,Los Angeles,585,asian,3
30,Tilt Coffee,Coffee Shop,34.048258,-118.246359,5856f788158b966de017c324,Los Angeles,33,casual,1
31,Kismet Falafel,Falafel Restaurant,34.050791,-118.249007,554a75cc498eccd15edaf98e,Los Angeles,84,asian,2
32,Sari Sari Store LA,Filipino Restaurant,34.051065,-118.249390,5956f0d0f5e9d7161f043456,Los Angeles,55,asian,1
37,Spring Street SmokeHouse,BBQ Joint,34.058379,-118.238509,4a7c7f3df964a520cbec1fe3,Los Angeles,92,american,2
39,Mitsuru Cafe,Japanese Restaurant,34.048959,-118.240001,4b3e9810f964a520789f25e3,Los Angeles,64,asian,2
40,Rakkan Ramen,Ramen Restaurant,34.049447,-118.239528,596448501987ec3cfd0626f0,Los Angeles,22,asian,1
41,La Noche Buena,Mexican Restaurant,34.057186,-118.238181,4ab99509f964a520f27f20e3,Los Angeles,25,latino,1
42,Patina Restaurant,French Restaurant,34.054712,-118.249590,4ad01a5af964a52095d720e3,Los Angeles,78,euro,2
43,Wolf & Crane Bar,Bar,34.047942,-118.239650,51aee770454a09a5e4e3b2f9,Los Angeles,162,bar,2
44,Hama Sushi,Sushi Restaurant,34.048527,-118.240500,49d97513f964a520395e1fe3,Los Angeles,105,asian,2
45,Maccheroni Republic,Italian Restaurant,34.050020,-118.248656,50d223c5e4b00439552865de,Los Angeles,200,euro,3
50,Little Tokyo Mall,Shopping Mall,34.049012,-118.240547,4cc4b82401fb236aaf9eadba,Los Angeles,48,None,1
51,Komasa,Japanese Restaurant,34.048499,-118.240424,4ad54f8cf964a520c70221e3,Los Angeles,75,asian,2
52,Cielito Lindo,Mexican Restaurant,34.058044,-118.237457,4b53787df964a5208b9e27e3,Los Angeles,120,latino,2
54,Spitz,Mediterranean Restaurant,34.048144,-118.239962,49ef5a6ef964a520a6681fe3,Los Angeles,154,euro,2
55,Shin-Sen-Gumi,Ramen Restaurant,34.048187,-118.239152,4e5b046a227188671508b714,Los Angeles,395,asian,3
56,Prime Pizza,Pizza Place,34.048063,-118.239393,5a14c1f9628c832160a43648,Los Angeles,9,euro,1
57,KazuNori: The Original Hand Roll Bar,Sushi Restaurant,34.047716,-118.247452,53d06bba498e6c801ea9816e,Los Angeles,327,asian,3
59,Bäco Mercat,Gastropub,34.047854,-118.247413,4eb4d3d31081376a2c1edadf,Los Angeles,482,bar,3
60,Bar Amá,Mexican Restaurant,34.048523,-118.248076,50c92ed6e4b08539f9ff721c,Los Angeles,357,latino,3
61,G&B Coffee,Coffee Shop,34.051006,-118.249356,51a8d473498ea68ee462260c,Los Angeles,384,casual,3
62,Zencu Sushi & Grill,Sushi Restaurant,34.049178,-118.240654,4a07bb56f964a52098731fe3,Los Angeles,32,asian,1
64,Sushi Zo,Sushi Restaurant,34.048148,-118.247188,522fe77511d2e9bbd1856537,Los Angeles,17,asian,1
65,Sarita's Pupuseria,Latin American Restaurant,34.050735,-118.248875,4aef41e4f964a520fcd621e3,Los Angeles,58,latino,1
67,Eggslut,Breakfast Spot,34.050635,-118.248678,527bf41911d2ff4cca3e912e,Los Angeles,740,casual,3
68,Chinchikurin Hiroshima Okonomiyaki,Japanese Restaurant,34.049464,-118.239715,5aa19448f96b2c6dc60bfaf2,Los Angeles,21,asian,1
69,Oomasa,Sushi Restaurant,34.049294,-118.239678,412d2800f964a520d80c1fe3,Los Angeles,106,asian,2
70,Otium,New American Restaurant,34.054312,-118.251214,563ac687cd101c7dff9cd41b,Los Angeles,269,american,3
72,Weller Court,Shopping Mall,34.050068,-118.242135,4bb796bd1261d13ab986e798,Los Angeles,37,None,1
73,Little Jewel of New Orleans,Cajun / Creole Restaurant,34.060036,-118.238260,53f105e5498e9e63662731bd,Los Angeles,140,None,2
74,Chado Tea Room,Tea Room,34.049219,-118.238580,4b77488cf964a520a88e2ee3,Los Angeles,34,None,1
76,Suehiro Cafe,Yoshoku Restaurant,34.049717,-118.239989,4a3c745df964a5208ea11fe3,Los Angeles,111,asian,2
77,Bar Clacson,Bar,34.049921,-118.249304,5865a033424f935d0b310727,Los Angeles,31,bar,1
79,Free Range LA,Food Truck,34.048229,-118.238097,5117f31ee4b03863cbbc1e7a,Los Angeles,24,casual,1
80,Philippe The Original,Sandwich Place,34.059622,-118.237013,4470358df964a52089331fe3,Los Angeles,982,casual,3
81,TOT / Teishokuya of Tokyo,Japanese Restaurant,34.048567,-118.240549,4f6dab16e4b09530ae838613,Los Angeles,23,asian,1
82,Mendocino Farms,Sandwich Place,34.052485,-118.251422,4a15b32ff964a520bb781fe3,Los Angeles,56,casual,1
84,Starbucks,Coffee Shop,34.049518,-118.241908,57fd4578498e20e69bc98c2a,Los Angeles,9,casual,1
85,Men Oh Tokushima Ramen,Ramen Restaurant,34.047238,-118.238668,506b47e3e4b010161f10b560,Los Angeles,130,asian,2
86,Mitsuru Sushi and Grill,Sushi Restaurant,34.050066,-118.240620,4b5b6561f964a520b2fa28e3,Los Angeles,12,asian,1
88,Twinkle Brown Sugar,Bubble Tea Shop,34.048207,-118.239313,4f418d14e4b0e408260f5cb8,Los Angeles,112,None,2
89,Sushi Gen,Sushi Restaurant,34.046849,-118.238520,4a087129f964a520c7731fe3,Los Angeles,235,asian,3
90,Ramón C. Cortines School of Visual and Perform...,High School,34.059485,-118.244042,4fc519a0e4b0452621553472,Los Angeles,10,None,1
91,Angels Flight - Upper Station,Train Station,34.051561,-118.250644,50a00eaf19a918cf99a8f624,Los Angeles,39,None,1
92,Hakata Ikkousha,Ramen Restaurant,34.047891,-118.239578,5932386367af3a528de0ad76,Los Angeles,32,asian,1
97,Midori Matcha,Food & Drink Shop,34.050011,-118.242124,5869aa300037eb49446d5351,Los Angeles,28,american,1
98,Monkey Pants,Kids Store,34.049009,-118.240494,508b4d36e4b0ad933b7a49d8,Los Angeles,8,None,1
99,Bicycle Coffee,Coffee Shop,34.048184,-118.240115,5b5a3567c03635002c97f1a1,Los Angeles,12,casual,1
1,Tender Greens,New American Restaurant,32.716082,-117.163925,51d0c254498e603aabbc5bae,San Diego,157,american,2
3,Grant Grill,American Restaurant,32.716125,-117.161084,40e0b100f964a52030021fe3,San Diego,76,american,2
5,WestBean Coffee Roasters,Coffee Shop,32.715736,-117.162460,54dcf93e498e72ab49cd0ba8,San Diego,62,casual,1
6,Dobson's Bar & Restaurant,American Restaurant,32.715400,-117.162741,40e0b100f964a52008021fe3,San Diego,34,american,1
8,Le Fontainbleau - The Westgate Hotel,French Restaurant,32.716267,-117.162452,4e4c4687bd413c4cc668273f,San Diego,9,euro,1
9,The Local Eatery and Drinking Hole,Bar,32.716501,-117.160933,4165d880f964a520791d1fe3,San Diego,150,bar,2
12,The Taco Stand Downtown,Taco Place,32.717749,-117.158497,568daf60498eaf94b8afbc5d,San Diego,77,latino,2
14,The Crab Hut,Seafood Restaurant,32.715802,-117.159871,4c48d7c7b5eec9b6e945efa3,San Diego,131,american,2
15,Rei Do Gado,Brazilian Restaurant,32.715202,-117.160940,4b933ab9f964a5204d3c34e3,San Diego,170,latino,2
17,Vin de Syrah Wine Parlor,Wine Bar,32.714723,-117.160040,4a3dd4d2f964a520b3a21fe3,San Diego,207,bar,3
21,Chef Miguel's Deli,Sandwich Place,32.716500,-117.158690,4bbce75f8a4fb713dc533c9d,San Diego,26,casual,1
22,Sushi 2,Sushi Restaurant,32.715731,-117.163122,4a9887fdf964a520882c20e3,San Diego,143,asian,2
23,Starbucks,Coffee Shop,32.715306,-117.161453,52869068498e3289da674749,San Diego,36,casual,1
25,Cocina 35 Old School Mexican,Mexican Restaurant,32.720279,-117.159258,556cd86c498e348960e5a64f,San Diego,41,latino,1
26,The Kebab Shop,Falafel Restaurant,32.720824,-117.165654,4f35d936e4b0a1f1952a21aa,San Diego,105,asian,2
28,Operacaffe,Italian Restaurant,32.714041,-117.160996,4abd87d6f964a520dc8a20e3,San Diego,36,euro,1
29,Superfly Tattoo & Body Piercing,Tattoo Parlor,32.715811,-117.159834,4b9da40ef964a520beb736e3,San Diego,3,None,1
34,Osetra the Fishhouse,Seafood Restaurant,32.714777,-117.160314,4bf8834db182c9b636ad775a,San Diego,64,american,2
35,Chipotle Mexican Grill,Mexican Restaurant,32.715021,-117.164296,4ee915df2c5b49765f15860b,San Diego,94,latino,2
36,Achilles Coffee Outdoor Cafe,Café,32.717678,-117.157378,59d9458f916bc1155f05ce54,San Diego,10,casual,1
38,Full Moon Sushi and Kitchen Bar,Sushi Restaurant,32.715117,-117.160260,5393d0e8498e57e15686179c,San Diego,34,asian,1
46,Stone Company Store,Pub,32.717810,-117.169327,52785f0f11d25028a33cfc74,San Diego,65,bar,2
47,Queenstown Public House,New American Restaurant,32.721800,-117.167297,4f57df61e4b0b09e31372326,San Diego,295,american,3
50,City Pizzeria,Pizza Place,32.717746,-117.159197,4bce5a44ef10952130128486,San Diego,18,euro,1
54,Buca di Beppo,Italian Restaurant,32.712895,-117.159095,44eb7237f964a520cb371fe3,San Diego,97,euro,2
57,SoleLuna Cafe,Café,32.720016,-117.158305,4e13825762e14518a91d8b22,San Diego,7,casual,1
58,Dog Haus Biergarten,Hot Dog Joint,32.715529,-117.156307,5734add2498e90770a893def,San Diego,30,casual,1
60,Empanada Kitchen,Empanada Restaurant,32.716517,-117.157137,5a7cc0631953f35cd30ab191,San Diego,8,None,1
61,Breakfast Republic,Breakfast Spot,32.712501,-117.158175,5895f33b3bd4ab768a550a90,San Diego,127,casual,2
62,Salvatore's Cucina Italiana,Italian Restaurant,32.712613,-117.164786,4b9328a6f964a520613834e3,San Diego,30,euro,1
63,Hodad's Downtown,Burger Joint,32.715552,-117.155845,4b3be509f964a520d27d25e3,San Diego,321,casual,3
65,Spike Africa's Fresh Fish Bar & Grill,Seafood Restaurant,32.715534,-117.160880,50e8ece5e4b044bde4882ff1,San Diego,119,american,2
66,Copa Vida,Coffee Shop,32.715697,-117.168531,5892465a9398ab157a750b84,San Diego,18,casual,1
67,Craft & Commerce,Gastropub,32.720875,-117.168964,57c8db30498e75e3ba174353,San Diego,104,bar,2
68,Isola Pizza Bar,Italian Restaurant,32.721200,-117.168336,4f887912e4b0b1c4aeda18f9,San Diego,104,euro,2
69,Noble Experiment,Speakeasy,32.712412,-117.157602,4b764958f964a520ba462ee3,San Diego,196,bar,3
71,Old Gallery Coffee House,Coffee Shop,32.717758,-117.158601,4b6223f0f964a52019382ae3,San Diego,19,casual,1
72,Achilles Coffee Roasters,Coffee Shop,32.719710,-117.158246,5734ae4bcd10494d763052fc,San Diego,22,casual,1
73,Lofty Coffee Little Italy Cafe And Bakery,Café,32.722115,-117.167341,589cbdd52c55ec4c239a9360,San Diego,83,casual,2
74,Ramen Yamadaya,Ramen Restaurant,32.715721,-117.159623,564ff470498ee3d910f427e5,San Diego,33,asian,1
75,False Idol,Tiki Bar,32.720878,-117.168870,57cca899498e646cd72b5539,San Diego,78,bar,2
76,Ironside Fish & Oyster,Seafood Restaurant,32.722721,-117.168453,5343742b11d22b61cbaab411,San Diego,525,american,3
78,El Dorado Cocktail Lounge,Cocktail Bar,32.715865,-117.154983,491be395f964a52073521fe3,San Diego,101,bar,2
79,Tacos El Cabron,Mexican Restaurant,32.710852,-117.161130,5a0e148fd0a1494ae8bd06bb,San Diego,31,latino,1
80,Richard Walker's Pancake House San Diego,Breakfast Spot,32.711029,-117.164882,46499c1cf964a520aa461fe3,San Diego,489,casual,3
81,Burger Lounge Little Italy,Burger Joint,32.722158,-117.168342,4a6bed30f964a52044d01fe3,San Diego,140,casual,2
82,Barleymash,Bar,32.711608,-117.160181,4ee7e3a102d5895bd6b461e0,San Diego,534,bar,3
83,Pho Xpress,Vietnamese Restaurant,32.717299,-117.159161,4b64e4c3f964a52004d82ae3,San Diego,35,asian,1
84,Fogo de Chão,Brazilian Restaurant,32.712315,-117.159506,51df2bc7920951789f296f3f,San Diego,204,latino,3
85,La Puerta,Mexican Restaurant,32.711093,-117.161181,4a2f333df964a520b7981fe3,San Diego,479,latino,3
86,Taka Sushi,Sushi Restaurant,32.711171,-117.159939,4a66bb44f964a520d2c81fe3,San Diego,131,asian,2
88,Vans,Shoe Store,32.713673,-117.163174,4ba7b01bf964a520d2a939e3,San Diego,5,None,1
89,Pokez Mexican Restaurant,Mexican Restaurant,32.714574,-117.155761,44e07ae1f964a520fa361fe3,San Diego,175,latino,2
90,Time Out Sports Tavern,American Restaurant,32.715840,-117.158586,4d360eebfe972c0f49a99ab3,San Diego,20,american,1
91,Tajima Ramen East Village,Ramen Restaurant,32.714553,-117.156398,5680b03a498e78a8fe2287dc,San Diego,54,asian,1
92,Vitality Tap,Juice Bar,32.712377,-117.163849,51956237498e5b3fcce3af52,San Diego,27,casual,1
93,Buon Appetito Restaurant,Italian Restaurant,32.722400,-117.168073,42a8d800f964a5201e251fe3,San Diego,116,euro,2
94,SoleLuna Cafe,Italian Restaurant,32.719913,-117.158480,4a2f0206f964a52096981fe3,San Diego,22,euro,1
95,Indigo Grill,American Restaurant,32.721737,-117.168237,41575800f964a520341d1fe3,San Diego,54,american,1
96,Sorrento Ristorante And Pizzeria,Italian Restaurant,32.722530,-117.168560,559f3d4b498e8674883281b4,San Diego,48,euro,1
97,Not Not Tacos,Taco Place,32.723081,-117.167730,5b51614c0a08ab002c39e193,San Diego,10,latino,1
98,The Lion's Share,Bar,32.711905,-117.169035,4ea9de56f9f45048e718d81f,San Diego,175,bar,2
99,Spill The Beans Coffee And Bagel,Coffee Shop,32.711511,-117.159538,59970ecdbfc6d003052f6210,San Diego,20,casual,1

In [15]:
# create dummies for linear regression modelling

# one hot encoding
reg_dataset = pd.get_dummies(raw_dataset[['categories_classified', 
                                          'city',]], 
                               prefix="", 
                               prefix_sep="")

# add name, ranking, and likes columns back to dataframe
reg_dataset['ranking'] = raw_dataset['ranking']
reg_dataset['likes'] = raw_dataset['likes']
reg_dataset['name'] = raw_dataset['name']

# move name column to the first column
reg_columns = [reg_dataset.columns[-1]] + list(reg_dataset.columns[:-1])
reg_dataset = reg_dataset[reg_columns]


reg_dataset.head()

,name,american,asian,bar,casual,euro,latino,Los Angeles,San Diego,San Francisco,ranking,likes
12,Nojo Ramen Tavern,0,1,0,0,0,0,0,0,1,3,351
13,The Beer Hall,0,0,1,0,0,0,0,0,1,3,291
14,Birba,0,0,1,0,0,0,0,0,1,2,132
16,Philz Coffee,0,0,0,1,0,0,0,0,1,3,480
17,Blue Bottle Coffee,0,0,0,1,0,0,0,0,1,3,457

# 3. Methodology

This project will utilize both linear and logistic regression machine learning methods to train and test the data. Namely, linear regression will be used in an attempt to predict the number of "likes" a new restaurant in this region will have. We will utilize the Sci-Kit Learn Package to run the model. 

We can also utilize logisitc regression as a classification method rather than direct prediction of the number of likes. Since the number of "likes" can be binned into different categories based on different percentile bins, it is also potentiallly possible to see which range of "likes" a new restaurant in this region will have. 

Since the "likes" are binned into multiple (more than 2) categories, the type of logistic regression will be multinomial. Additionally, although the ranges are indeed discrete categories, they are also ordinal in nature. Therefore the logistic regression will need to be specified as being both multinomial and ordinal. This can be done through the Sci-Kit Learn Package as well.

# 4. Results

## 4.1 Linear Regression Results

A linear regression model was trained on a random subsample of 80% of the sample and then tested on the other 20%. To see if this is a reasonable model. the residual sum of squares score and variance score were both calculated (56861.68.64 and 0.08 respectively). Given the low variance score, this is probably not a valid/good way of modelling the data. Therefore, we move on to logistic regression.

In [16]:
# Multiple Linear Regression

msk = np.random.rand(len(reg_dataset)) < 0.8
train = reg_dataset[msk]
test = reg_dataset[~msk]

regr = linear_model.LinearRegression()
x = np.asanyarray(train[['american', 'asian', 'bar', 'casual',
                         'euro', 'latino', 'Los Angeles', 
                         'San Diego', 'San Francisco']])
y = np.asanyarray(train[['likes']])
regr.fit (x, y)
# The coefficients
print ('Coefficients: ', regr.coef_)

Coefficients:  [[ 223.91573312  127.15312213  182.25625305  178.37190607  171.1504989
   150.8437457   -24.65195511 -106.46946398  131.1214191 ]]

In [17]:
# Multiple Linear Regression Prediction Capabilities

y_hat= regr.predict(test[['american', 'asian', 'bar', 'casual',
                         'euro', 'latino', 'Los Angeles', 
                         'San Diego', 'San Francisco']])
x = np.asanyarray(test[['american', 'asian', 'bar', 'casual',
                         'euro', 'latino', 'Los Angeles', 
                         'San Diego', 'San Francisco']])
y = np.asanyarray(test[['likes']])
print("Residual sum of squares: %.2f"
      % np.mean((y_hat - y) ** 2))

# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % regr.score(x, y))

Residual sum of squares: 56861.68
Variance score: 0.08

## 4.2 Logistic Regression Results

A multinomial ordinal logisitc regression model was trained on a random subsample of 80% of the sample and then tested on the other 20%. To see if this is a reasonable model, its jaccard similarity score and log-loss were calculated (44% and 1.18 respectively). Although this is not a perfect prediction, a similarity of 44% between the training set and test set is a reasonable result. The classification report is also printed later on below.
<br>

Given the modestly accurate ability of this model, we can also run the model on the full dataset. The coefficients show that opening a restaurant in San Francisco, opening a bar, or serving cuisine that is american or asian in nature, are associated negatively with "likes."

In [18]:
# Multinomial Ordinal Logistic Regression

x_train = np.asanyarray(train[['american', 'asian', 'bar', 'casual',
                         'euro', 'latino', 'Los Angeles', 
                         'San Diego', 'San Francisco']])
y_train = np.asanyarray(train['ranking'])

x_test = np.asanyarray(test[['american', 'asian', 'bar', 'casual',
                         'euro', 'latino', 'Los Angeles', 
                         'San Diego', 'San Francisco']])
y_test = np.asanyarray(test['ranking'])


# LR = LogisticRegression(C=0.01, solver='liblinear').fit(x_train, y_train)
# LR

mul_ordinal = linear_model.LogisticRegression(multi_class='multinomial',
                                              solver='newton-cg',
                                              fit_intercept=True).fit(x_train,
                                                                      y_train)

mul_ordinal

coef = mul_ordinal.coef_[0]
print (coef)

[-0.59187287 -0.54326292 -1.4351762  -0.21272491  0.03325283 -0.40066405
  0.24740373  0.45721639 -0.70461337]

In [24]:
# Multinomial Ordinal Logistic Regression Prediction Capabilities

yhat = mul_ordinal.predict(x_test)
yhat

yhat_prob = mul_ordinal.predict_proba(x_test)
yhat_prob


jaccard_similarity_score(y_test, yhat)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)

0.4482758620689655

In [25]:
log_loss(y_test, yhat_prob)

1.181064441012519

In [21]:
# Exploration of Coefficient Magnitudes of Full Dataset

x_all = np.asanyarray(reg_dataset[['american', 'asian', 'bar', 'casual',
                                   'euro', 'latino', 'Los Angeles', 
                                   'San Diego', 'San Francisco']])
y_all = np.asanyarray(reg_dataset['ranking'])



LR = linear_model.LogisticRegression(multi_class='multinomial',
                                            solver='newton-cg',
                                            fit_intercept=True).fit(x_all,
                                                                    y_all)

LR

coef = LR.coef_[0]
print (coef)

[-0.75034451 -0.48619597 -1.11971989 -0.19106288 -0.14703687 -0.57601186
  0.1885658   0.41588959 -0.60445322]

In [22]:
print (classification_report(y_test, yhat))

              precision    recall  f1-score   support

           1       0.44      0.67      0.53        12
           2       1.00      0.09      0.17        11
           3       0.40      0.67      0.50         6

    accuracy                           0.45        29
   macro avg       0.61      0.47      0.40        29
weighted avg       0.65      0.45      0.39        29

## 5. Discussion

The first thing to note is that given the data, logistic regression presents a better fit for the data over linear regression. Using logistic regression we were able to obtain a Jaccard Similarity Score of 44%, which although not perfect, is more reasonable than the low variance score obtained from the linear regression. As stated before, please note that for the purposes of this project, we are assumming that likes are a good proxy for how well a new restaurant will do in terms of brand, image and by extension how well the restaurant will perform business-wise. Whether or not these assumptions hold up in a real-life scenario is up for discussion, but this project does contain limitations in scope due to the amount of data that can be fetched from the FourSquare API. 

<br>

As such, to obtain insights into this data, we can proceed with breaking down the results of the logistic regression model. The results showed that the precision score for classifying whether the new restaurant would fall into classes 1 and 2  were 44%, 40% Therefore, the model is better at predicting if a restaurant will fall into the best or worst percentile of likes. This is good as we are mostly concerned with whether the restuarant will perform well or not so the high accuracy of predictions for the two extremum is a welcome feature. This allows us to fairly accurately predict the general performance of the business opportunity. Different binning methods for the classes were attempted, but the use of 3 bins by far yielded the best Jaccard Similarity Score. 

<br>

Additionally, not only are we attempting to predict the general business performance but also pull insights to inform on business strategy. In this case strategy insight can be gleamed from the coefficient values from running the logistic regressin on the full dataset. As such, we can see that opening a restaurant in San Francisco, opening a bar, or serving cuisine that is american or asian in nature, are associated negatively with "likes." This suggests that the business opportunity should be opening a restaurant in either Los Angeles or San Diego, with a cuisine that is European, Latino, or casual in nature would be the best approach for maximizing likes.

## 6. Conclusion

In conclusion, after analyzing restaurant "likes" in California from 300 restaurants, we can conclude that the approach to best take in regards to maximizing business performance (as measured by "likes") is to open a restaurant that is either European, Latino, or casual and that opening the venue in either Los Angeles or San Diego rather than San Francisco would be the best approach. Additionally, the predictive capabilities of the logistic regression prediction model are most accurate for classifying whether a restaurant will fall in either the best or worst classes when the data is binned into 3 classes.